### ISSUE TITLE
Feedback and Suggestions Regarding Mod Package and AE Fixes

### ISSUE THREAD

**Issue by Yakrel** [ElmoDFGD/ElmoRim#25]
Hello,

I appreciate the great effort you've put into creating this mod package. While going through your list of installed mods, I've noticed a couple of things I'd like to discuss.

Firstly, I'm interested in the idea of having an 'Enairim suite' version of your mod package. I've thought about removing the 'Simonrim suite' myself, but I'm worried that doing so might result in important mods being left out or certain components being overlooked.

Secondly, I've seen that there are fixes available for AE, like the 'Unofficial Skyrim Creation Club Content Patches.' I'd like to suggest the possibility of adding an extra branch to MO2 that includes these fixes and maybe other relevant mods. This could be really helpful for those of us who are using AE.

Thank you for considering these suggestions and thoughts.

**Comment by ElmoDFGD** [comment]
Hi!

Thank you for the feedback! I am always happy when someone finds ElmoRim worth taking the time to provide suggestions about.

I prefer SimonRim over EnaiRim because I feel it is more streamlined, which fits the heavy gameplay/combat focus of the list.

With that said, ElmoRim is pretty simple in its setup so if you are familiar with xedit it shouldn't be to hard to do yourself.

While I have entertained the idea of branches/profiles I am not prepared to explore this at the moment. Elmorim is still in active development and before I have put out a few more updates I want to keep the setup as simple as possible.

/Elmo

**Comment by Yakrel** [comment]
Allright thank you.
